feature_info:
  feature_names: Unknown
  metadata:
    bolag_features: &id001
    - Bolag_Bergslagen
    - Bolag_Blekinge
    - Bolag_Dalarna
    - Bolag_Gotland
    - "Bolag_G\xE4vleborg"
    - "Bolag_G\xF6inge-Kristianstad"
    - "Bolag_G\xF6teborg och Bohusl\xE4n"
    - Bolag_Halland
    - "Bolag_J\xE4mtland"
    - "Bolag_J\xF6nk\xF6ping"
    - Bolag_Kalmar
    - Bolag_Kronoberg
    - Bolag_Norrbotten
    - Bolag_Sak
    - Bolag_Skaraborg
    - "Bolag_Sk\xE5ne"
    - Bolag_Stockholm
    - "Bolag_S\xF6dermanland"
    - Bolag_Uppsala
    - "Bolag_V\xE4rmland"
    - "Bolag_V\xE4sterbotten"
    - "Bolag_V\xE4sternorrland"
    - "Bolag_\xC4lvsborg"
    - "Bolag_\xD6stg\xF6ta"
    - "Bolag_\xD6vrigt"
    categorical_features: &id002
    - Dialog
    - Syfte
    - Product
    dummy_dialog_map:
      BNK: Dialog_BNK
      BO: Dialog_BO
      FNO: Dialog_FNO
      FRD: Dialog_FRD
      LIV: Dialog_LIV
    dummy_product_map:
      BO_: Product_BO_
      BO_BR_: Product_BO_BR_
      BO_HR_: Product_BO_HR_
      BO_VH_: Product_BO_VH_
      B_: Product_B_
      B_B_: Product_B_B_
      B_K_: Product_B_K_
      B_PL_: Product_B_PL_
      B_S_: Product_B_S_
      L_P_: Product_L_P_
      M_PB_: Product_M_PB_
      M_PB_MT_: Product_M_PB_MT_
      M_PB_PR_: Product_M_PB_PR_
      P_: Product_P_
      P_60_: Product_P_60_
      P_OSV_: Product_P_OSV_
    dummy_syfte_map:
      AVS_P: Syfte_AVS_P
      VLK: Syfte_VLK
      VRD: Syfte_VRD
      VRD_I: Syfte_VRD_I
      VRD_S: Syfte_VRD_S
      VXA: Syfte_VXA
      VXA_K: Syfte_VXA_K
      VXA_M: Syfte_VXA_M
    feature_sets:
      legacy:
        bolag: *id001
        categorical: *id002
        numerical: &id003
        - Min_age
        - Max_age
        - Subject_length
        - Num_words
        - Has_exclamation
        - Has_question
      v2:
        bolag: *id001
        categorical: *id002
        numerical: &id004
        - Min_age
        - Max_age
        - Subject_length
        - Subject_num_words
        - Subject_has_exclamation
        - Subject_has_question
        - Preheader_length
        - Preheader_num_words
        - Preheader_has_exclamation
        - Preheader_has_question
    include_preheader: true
    legacy_numerical_features: *id003
    v2_numerical_features: *id004
model_info:
  created_at: '2025-03-19 10:07:17'
  feature_count: Unknown
  model_parameters:
    base_score: null
    booster: null
    callbacks: null
    colsample_bylevel: null
    colsample_bynode: null
    colsample_bytree: null
    device: null
    early_stopping_rounds: null
    enable_categorical: false
    eval_metric: null
    feature_types: null
    gamma: null
    grow_policy: null
    importance_type: null
    interaction_constraints: null
    learning_rate: 0.04
    max_bin: null
    max_cat_threshold: null
    max_cat_to_onehot: null
    max_delta_step: null
    max_depth: 8
    max_leaves: null
    min_child_weight: null
    missing: .nan
    monotone_constraints: null
    multi_strategy: null
    n_estimators: 200
    n_jobs: null
    num_parallel_tree: null
    objective: reg:squarederror
    random_state: 42
    reg_alpha: null
    reg_lambda: 1.7
    sampling_method: null
    scale_pos_weight: null
    subsample: null
    tree_method: null
    validate_parameters: null
    verbosity: null
  version: 25.03.19
  xgboost_version: xgboost.sklearn
performance_metrics:
  cross_validation:
    mae:
      mean: !!python/object/apply:numpy.core.multiarray.scalar
      - &id005 !!python/object/apply:numpy.dtype
        args:
        - f8
        - false
        - true
        state: !!python/tuple
        - 3
        - <
        - null
        - null
        - null
        - -1
        - -1
        - 0
      - !!binary |
        Fzo3DiN8wD8=
      scores:
      - 0.08019461133548722
      - 0.1449626029050672
      - 0.22342587534947292
      - 0.13704624993425185
      - 0.05831245363746814
      std: !!python/object/apply:numpy.core.multiarray.scalar
      - *id005
      - !!binary |
        5nY/GYqDrT8=
    mse:
      mean: !!python/object/apply:numpy.core.multiarray.scalar
      - *id005
      - !!binary |
        Wvkcz3xqvz8=
      scores:
      - 0.013400486179366128
      - 0.13708011639729878
      - 0.2716857719239669
      - 0.1793075083776573
      - 0.012119221316071502
      std: !!python/object/apply:numpy.core.multiarray.scalar
      - *id005
      - !!binary |
        /XjRtlOLuT8=
    r2:
      mean: !!python/object/apply:numpy.core.multiarray.scalar
      - *id005
      - !!binary |
        OA9jgHCl9r8=
      scores:
      - 0.49666958324019217
      - -0.0871592217725361
      - -0.37107727551894065
      - -7.092567019998462
      - -0.02281853058575445
      std: !!python/object/apply:numpy.core.multiarray.scalar
      - *id005
      - !!binary |
        UsHbfazRBkA=
    rmse:
      mean: !!python/object/apply:numpy.core.multiarray.scalar
      - *id005
      - !!binary |
        MYSXMs640z8=
      scores:
      - !!python/object/apply:numpy.core.multiarray.scalar
        - *id005
        - !!binary |
          J5J0ZHqivT8=
      - !!python/object/apply:numpy.core.multiarray.scalar
        - *id005
        - !!binary |
          L11PChGy1z8=
      - !!python/object/apply:numpy.core.multiarray.scalar
        - *id005
        - !!binary |
          Sc/dtvSt4D8=
      - !!python/object/apply:numpy.core.multiarray.scalar
        - *id005
        - !!binary |
          NsL5K8IZ2z8=
      - !!python/object/apply:numpy.core.multiarray.scalar
        - *id005
        - !!binary |
          zclO/64uvD8=
      std: !!python/object/apply:numpy.core.multiarray.scalar
      - *id005
      - !!binary |
        jdMBYIVTxT8=
  test:
    mae: 0.09699727223477722
    mse: 0.08002940360426417
    r2: 0.24442246014985358
    rmse: !!python/object/apply:numpy.core.multiarray.scalar
    - *id005
    - !!binary |
      +IKYUPIa0j8=
  training:
    train_samples: 124
