feature_info:
  feature_names: Unknown
  metadata:
    bolag_features: &id001
    - Bolag_Bergslagen
    - Bolag_Blekinge
    - Bolag_Dalarna
    - Bolag_Gotland
    - "Bolag_G\xE4vleborg"
    - "Bolag_G\xF6inge-Kristianstad"
    - "Bolag_G\xF6teborg och Bohusl\xE4n"
    - Bolag_Halland
    - "Bolag_J\xE4mtland"
    - "Bolag_J\xF6nk\xF6ping"
    - Bolag_Kalmar
    - Bolag_Kronoberg
    - Bolag_Norrbotten
    - Bolag_Sak
    - Bolag_Skaraborg
    - "Bolag_Sk\xE5ne"
    - Bolag_Stockholm
    - "Bolag_S\xF6dermanland"
    - Bolag_Uppsala
    - "Bolag_V\xE4rmland"
    - "Bolag_V\xE4sterbotten"
    - "Bolag_V\xE4sternorrland"
    - "Bolag_\xC4lvsborg"
    - "Bolag_\xD6stg\xF6ta"
    - "Bolag_\xD6vrigt"
    categorical_features: &id002
    - Dialog
    - Syfte
    - Product
    dummy_dialog_map:
      BNK: Dialog_BNK
      BO: Dialog_BO
      FNO: Dialog_FNO
      FRD: Dialog_FRD
      LIV: Dialog_LIV
    dummy_product_map:
      BO_: Product_BO_
      BO_BR_: Product_BO_BR_
      BO_HR_: Product_BO_HR_
      BO_VH_: Product_BO_VH_
      B_: Product_B_
      B_B_: Product_B_B_
      B_K_: Product_B_K_
      B_PL_: Product_B_PL_
      B_S_: Product_B_S_
      L_P_: Product_L_P_
      M_PB_: Product_M_PB_
      M_PB_MT_: Product_M_PB_MT_
      M_PB_PR_: Product_M_PB_PR_
      P_: Product_P_
      P_60_: Product_P_60_
      P_OSV_: Product_P_OSV_
    dummy_syfte_map:
      AVS_P: Syfte_AVS_P
      VLK: Syfte_VLK
      VRD: Syfte_VRD
      VRD_I: Syfte_VRD_I
      VRD_S: Syfte_VRD_S
      VXA: Syfte_VXA
      VXA_K: Syfte_VXA_K
      VXA_M: Syfte_VXA_M
    feature_sets:
      legacy:
        bolag: *id001
        categorical: *id002
        numerical: &id003
        - Min_age
        - Max_age
        - Subject_length
        - Num_words
        - Has_exclamation
        - Has_question
      v2:
        bolag: *id001
        categorical: *id002
        numerical: &id004
        - Min_age
        - Max_age
        - Subject_length
        - Subject_num_words
        - Subject_has_exclamation
        - Subject_has_question
        - Preheader_length
        - Preheader_num_words
        - Preheader_has_exclamation
        - Preheader_has_question
    include_preheader: true
    legacy_numerical_features: *id003
    v2_numerical_features: *id004
model_info:
  created_at: '2025-03-18 16:18:38'
  feature_count: Unknown
  model_parameters:
    base_score: null
    booster: null
    callbacks: null
    colsample_bylevel: null
    colsample_bynode: null
    colsample_bytree: null
    device: null
    early_stopping_rounds: null
    enable_categorical: false
    eval_metric: null
    feature_types: null
    gamma: null
    grow_policy: null
    importance_type: null
    interaction_constraints: null
    learning_rate: 0.14
    max_bin: null
    max_cat_threshold: null
    max_cat_to_onehot: null
    max_delta_step: null
    max_depth: 7
    max_leaves: null
    min_child_weight: null
    missing: .nan
    monotone_constraints: null
    multi_strategy: null
    n_estimators: 150
    n_jobs: null
    num_parallel_tree: null
    objective: reg:squarederror
    random_state: 42
    reg_alpha: null
    reg_lambda: 0.7
    sampling_method: null
    scale_pos_weight: null
    subsample: null
    tree_method: null
    validate_parameters: null
    verbosity: null
  version: 25.03.18
  xgboost_version: xgboost.sklearn
performance_metrics:
  cross_validation:
    mae:
      mean: !!python/object/apply:numpy.core.multiarray.scalar
      - &id005 !!python/object/apply:numpy.dtype
        args:
        - f8
        - false
        - true
        state: !!python/tuple
        - 3
        - <
        - null
        - null
        - null
        - -1
        - -1
        - 0
      - !!binary |
        TS5yr6o6wD8=
      scores:
      - 0.07609272938215275
      - 0.14506517109400566
      - 0.22893820770360168
      - 0.13945992410022107
      - 0.04439580176448227
      std: !!python/object/apply:numpy.core.multiarray.scalar
      - *id005
      - !!binary |
        ACALE5NOsD8=
    mse:
      mean: !!python/object/apply:numpy.core.multiarray.scalar
      - *id005
      - !!binary |
        7pKbk4e5vz8=
      scores:
      - 0.011810626620222116
      - 0.14350896817166994
      - 0.28053908747565065
      - 0.17808393104151704
      - 0.005680921546967664
      std: !!python/object/apply:numpy.core.multiarray.scalar
      - *id005
      - !!binary |
        aRlAjaCzuj8=
    r2:
      mean: !!python/object/apply:numpy.core.multiarray.scalar
      - *id005
      - !!binary |
        mPg4ooXY9L8=
      scores:
      - 0.5563856759089562
      - -0.13814535802339556
      - -0.4157560221457941
      - -7.037344114463403
      - 0.5205507286728935
      std: !!python/object/apply:numpy.core.multiarray.scalar
      - *id005
      - !!binary |
        YA+I9C8iB0A=
    rmse:
      mean: !!python/object/apply:numpy.core.multiarray.scalar
      - *id005
      - !!binary |
        tu6n8tJi0z8=
      scores:
      - !!python/object/apply:numpy.core.multiarray.scalar
        - *id005
        - !!binary |
          /MfslTzSuz8=
      - !!python/object/apply:numpy.core.multiarray.scalar
        - *id005
        - !!binary |
          /LMld64+2D8=
      - !!python/object/apply:numpy.core.multiarray.scalar
        - *id005
        - !!binary |
          NG/pSPjy4D8=
      - !!python/object/apply:numpy.core.multiarray.scalar
        - *id005
        - !!binary |
          L6T/8QsC2z8=
      - !!python/object/apply:numpy.core.multiarray.scalar
        - *id005
        - !!binary |
          6wNRc5JLsz8=
      std: !!python/object/apply:numpy.core.multiarray.scalar
      - *id005
      - !!binary |
        pVZySXj1xj8=
  test:
    mae: 0.1551028705731702
    mse: 0.20556424553648067
    r2: -0.9407832612578622
    rmse: !!python/object/apply:numpy.core.multiarray.scalar
    - *id005
    - !!binary |
      tGbemV8E3T8=
  training:
    train_samples: 124
