created_at: '2025-03-19 11:20:14'
feature_count: 74
feature_names:
- Dialog_BNK
- Dialog_BO
- Dialog_FNO
- Dialog_FRD
- Dialog_LIV
- Syfte_AVS_P
- Syfte_VLK
- Syfte_VRD
- Syfte_VRD_I
- Syfte_VRD_S
- Syfte_VXA
- Syfte_VXA_K
- Syfte_VXA_M
- Product_BO_
- Product_BO_BR_
- Product_BO_HR_
- Product_BO_VH_
- Product_B_
- Product_B_B_
- Product_B_K_
- Product_B_PL_
- Product_B_S_
- Product_L_P_
- Product_M_PB_
- Product_M_PB_MT_
- Product_M_PB_PR_
- Product_P_
- Product_P_60_
- Product_P_OSV_
- Min_age
- Max_age
- Subject_length
- Subject_num_words
- Subject_has_exclamation
- Subject_has_question
- Subject_caps_ratio
- Subject_avg_word_len
- Subject_num_special_chars
- Subject_first_word_len
- Subject_last_word_len
- Preheader_length
- Preheader_num_words
- Preheader_has_exclamation
- Preheader_has_question
- Preheader_caps_ratio
- Preheader_avg_word_len
- Preheader_num_special_chars
- Subject_preheader_length_ratio
- Subject_preheader_words_ratio
- Bolag_Bergslagen
- Bolag_Blekinge
- Bolag_Dalarna
- Bolag_Gotland
- "Bolag_G\xE4vleborg"
- "Bolag_G\xF6inge-Kristianstad"
- "Bolag_G\xF6teborg och Bohusl\xE4n"
- Bolag_Halland
- "Bolag_J\xE4mtland"
- "Bolag_J\xF6nk\xF6ping"
- Bolag_Kalmar
- Bolag_Kronoberg
- Bolag_Norrbotten
- Bolag_Sak
- Bolag_Skaraborg
- "Bolag_Sk\xE5ne"
- Bolag_Stockholm
- "Bolag_S\xF6dermanland"
- Bolag_Uppsala
- "Bolag_V\xE4rmland"
- "Bolag_V\xE4sterbotten"
- "Bolag_V\xE4sternorrland"
- "Bolag_\xC4lvsborg"
- "Bolag_\xD6stg\xF6ta"
- "Bolag_\xD6vrigt"
feature_set: v2
include_preheader: true
model_parameters:
  learning_rate: 0.1
  max_depth: 5
  n_estimators: 100
  random_state: 42
  reg_lambda: 1.0
sample_weights:
  threshold: 0.5
  weight_high: 2.0
  weight_low: 1.0
test_samples: 32
training_samples: 124
version: 25.03.19
